#!/bin/bash

echo "=== Instrucciones para actualizar las reglas de Firebase Database ==="
echo ""
echo "Para resolver el error de 'permission_denied', necesitas actualizar las reglas en la consola de Firebase:"
echo ""
echo "1. Abre la consola de Firebase: https://console.firebase.google.com/"
echo "2. Selecciona tu proyecto FamilOS"
echo "3. Ve a 'Realtime Database' en el menú lateral"
echo "4. Haz clic en la pestaña 'Reglas'"
echo "5. Reemplaza las reglas existentes con el contenido del archivo 'firebase-database-rules.json'"
echo ""
echo "Reglas corregidas (copia y pega esto en la consola):"
echo "================================================================"
cat /Users/camnr/Documents/AppMacOs/FamilOS/firebase-database-rules.json
echo ""
echo "================================================================"
echo ""
echo "TEMPORALMENTE, puedes usar reglas más permisivas para pruebas:"
echo ""
cat /Users/camnr/Documents/AppMacOs/FamilOS/firebase-rules-temp.json
echo ""
echo "================================================================"
echo ""
echo "6. Haz clic en 'Publicar' para aplicar las reglas"
echo ""
echo "Una vez actualizadas las reglas, el error de permission_denied debería resolverse."
echo ""
echo "NOTA: Las reglas temporales son menos seguras. Úsalas solo para pruebas y"
echo "      reemplázalas con las reglas completas cuando sea posible."
